export const PERFUME_CATALOG = [
  {
    id: "hermes-nile",
    brand: "Hermes",
    brandCn: "爱马仕",
    name: "Un Jardin sur le Nil",
    nameCn: "尼罗河花园",
    family: "柑橘水生绿意调",
    notes: ["青芒果", "莲花", "西克莫木", "青草", "水感"],
    palette: ["#6fe7c8", "#f9d75d", "#4a9cff", "#dfffe8"],
    motifs: ["river", "grass", "citrus", "petal"],
    tempo: 94,
    tags: ["清新", "水生", "绿意", "通勤", "春夏"],
    occasions: ["daily", "work", "summer"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.hermes.com/us/en/product/un-jardin-sur-le-nil-eau-de-toilette-V20396/",
    description: "清澈、绿意、带一点果酸的水边气味，适合想要干净但不无聊的人。"
  },
  {
    id: "hermes-terre",
    brand: "Hermes",
    brandCn: "爱马仕",
    name: "Terre d'Hermes",
    nameCn: "大地",
    family: "木质柑橘矿物调",
    notes: ["橙子", "葡萄柚", "胡椒", "雪松", "矿物感"],
    palette: ["#d8843d", "#6c4b34", "#f2c27a", "#25201c"],
    motifs: ["earth", "citrus", "stone", "wood"],
    tempo: 76,
    tags: ["木质", "成熟", "商务", "中性", "秋冬"],
    occasions: ["work", "date", "formal"],
    intensity: "中高",
    gender: "偏男香",
    link: "https://www.hermes.com/us/en/category/perfume-and-beauty/perfume/men-perfumes/terre-d-hermes/",
    description: "柑橘开场后落到木质和矿物感，适合成熟、稳、干净的形象。"
  },
  {
    id: "hermes-twilly",
    brand: "Hermes",
    brandCn: "爱马仕",
    name: "Twilly d'Hermes",
    nameCn: "丝巾",
    family: "姜花晚香玉檀木调",
    notes: ["姜", "晚香玉", "檀木", "白花", "辛香"],
    palette: ["#ff8a78", "#f9c0a8", "#8a453a", "#fff0e8"],
    motifs: ["ribbon", "flower", "spice", "silk"],
    tempo: 88,
    tags: ["甜辛", "活泼", "白花", "约会", "年轻"],
    occasions: ["date", "party", "daily"],
    intensity: "中",
    gender: "女香",
    link: "https://www.hermes.com/us/en/category/perfume-and-beauty/perfume/women-perfumes/twilly-d-hermes/",
    description: "有姜的明亮辛感，也有白花和檀木的柔软，适合灵动但不幼稚的气质。"
  },
  {
    id: "byredo-bal",
    brand: "Byredo",
    brandCn: "Byredo",
    name: "Bal d'Afrique",
    nameCn: "非洲之舞",
    family: "柑橘花香木质调",
    notes: ["佛手柑", "橙花", "紫罗兰", "雪松", "香根草"],
    palette: ["#f2c84b", "#f47f45", "#2f5f4f", "#fff4d2"],
    motifs: ["sun", "citrus", "dance", "wood"],
    tempo: 104,
    tags: ["明亮", "高级", "扩香", "社交", "春夏"],
    occasions: ["daily", "party", "work"],
    intensity: "中",
    gender: "中性",
    link: "https://www.byredo.com/us_en/perfume/best-sellers/bal-d-afrique/",
    description: "明亮的柑橘花香和干净木质，适合想要存在感但不压人的人。"
  },
  {
    id: "byredo-gypsy",
    brand: "Byredo",
    brandCn: "Byredo",
    name: "Gypsy Water",
    nameCn: "流浪者之歌",
    family: "柑橘焚香木质调",
    notes: ["佛手柑", "柠檬", "杜松子", "焚香", "檀木", "香草"],
    palette: ["#d8b46a", "#7e6b53", "#eef0df", "#2f2a24"],
    motifs: ["forest", "incense", "campfire", "citrus"],
    tempo: 82,
    tags: ["木质", "自由", "温暖", "中性", "秋冬"],
    occasions: ["daily", "travel", "date"],
    intensity: "中",
    gender: "中性",
    link: "https://www.byredo.com/us_en/perfume/best-sellers/gypsy-water/",
    description: "柑橘、焚香、木质和香草的组合，像户外、自由和轻微烟火气。"
  },
  {
    id: "byredo-mojave",
    brand: "Byredo",
    brandCn: "Byredo",
    name: "Mojave Ghost",
    nameCn: "无人区玫瑰之外的莫哈维之影",
    family: "柔木花果麝香调",
    notes: ["黄葵籽", "紫罗兰", "檀木", "木兰", "琥珀"],
    palette: ["#d8c3a5", "#b58f83", "#ede2d1", "#5b5148"],
    motifs: ["desert", "violet", "sand", "ghost"],
    tempo: 72,
    tags: ["柔和", "木质", "干净", "高级", "通勤"],
    occasions: ["daily", "work", "date"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.byredo.com/us_en/perfume/best-sellers/mojave-ghost/",
    description: "柔软木质和淡淡花果气，低调、干净、很适合日常。"
  },
  {
    id: "byredo-blanche",
    brand: "Byredo",
    brandCn: "Byredo",
    name: "Blanche",
    nameCn: "白色浪漫",
    family: "醛香白花麝香调",
    notes: ["醛", "玫瑰", "紫罗兰", "檀木", "麝香"],
    palette: ["#f7f7f2", "#dbe6e4", "#b7c8c2", "#ffffff"],
    motifs: ["linen", "soap", "skin", "white"],
    tempo: 68,
    tags: ["皂感", "干净", "白衬衫", "通勤", "亲肤"],
    occasions: ["daily", "work", "clean"],
    intensity: "轻",
    gender: "中性",
    link: "https://www.byredo.com/us_en/perfume/best-sellers/blanche/",
    description: "像干净床单和白衬衫的皂感麝香，适合不想打扰别人但想闻起来洁净。"
  },
  {
    id: "diptyque-philosykos",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    name: "Philosykos",
    nameCn: "希腊无花果",
    family: "无花果绿叶木质调",
    notes: ["无花果叶", "无花果树汁", "无花果木", "黑胡椒", "雪松"],
    palette: ["#85a66f", "#d9e6bf", "#5b6f45", "#f7f1dd"],
    motifs: ["fig", "leaf", "tree", "milk"],
    tempo: 86,
    tags: ["绿意", "奶感", "自然", "春夏", "文艺"],
    occasions: ["daily", "summer", "travel"],
    intensity: "中",
    gender: "中性",
    link: "https://www.diptyqueparis.com/en_us/p/philosykos-eau-de-parfum-75ml-1.html",
    description: "无花果叶、树汁和木质感，像坐在树荫下，清绿又有一点奶感。"
  },
  {
    id: "diptyque-do-son",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    name: "Do Son",
    nameCn: "杜桑",
    family: "晚香玉白花调",
    notes: ["晚香玉", "橙花", "茉莉", "海风", "麝香"],
    palette: ["#f7f0e8", "#f9c7d4", "#b6dbe8", "#ffffff"],
    motifs: ["tuberose", "sea", "white-flower", "breeze"],
    tempo: 74,
    tags: ["白花", "温柔", "海风", "约会", "女性"],
    occasions: ["date", "daily", "spring"],
    intensity: "中",
    gender: "女香",
    link: "https://www.diptyqueparis.com/en_us/l/fragrances.html",
    description: "白花和海风感，温柔但有存在感，适合喜欢晚香玉的人。"
  },
  {
    id: "diptyque-tamdao",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    name: "Tam Dao",
    nameCn: "檀道",
    family: "檀香木质调",
    notes: ["檀香", "雪松", "柏木", "玫瑰木", "琥珀"],
    palette: ["#8b6b4e", "#d5c1a3", "#3f3329", "#f1e6d0"],
    motifs: ["sandalwood", "temple", "smoke", "wood"],
    tempo: 64,
    tags: ["檀香", "安静", "木质", "冥想", "秋冬"],
    occasions: ["work", "night", "quiet"],
    intensity: "中",
    gender: "中性",
    link: "https://www.diptyqueparis.com/en_us/l/fragrances.html",
    description: "安静的檀香与木质感，适合想要克制、沉稳、留白的人。"
  },
  {
    id: "chanel-n5",
    brand: "Chanel",
    brandCn: "香奈儿",
    name: "N°5 Eau de Parfum",
    nameCn: "五号",
    family: "醛香花香调",
    notes: ["醛", "依兰", "玫瑰", "茉莉", "檀香"],
    palette: ["#f8e7b8", "#ffffff", "#d7bb74", "#191919"],
    motifs: ["gold", "flower", "powder", "classic"],
    tempo: 70,
    tags: ["经典", "粉感", "正式", "成熟", "礼物"],
    occasions: ["formal", "gift", "night"],
    intensity: "中高",
    gender: "女香",
    link: "https://www.chanel.com/us/fragrance/",
    description: "经典醛香花香，正式、优雅、复古感强，适合作为经典入门。"
  },
  {
    id: "chanel-coco-mademoiselle",
    brand: "Chanel",
    brandCn: "香奈儿",
    name: "Coco Mademoiselle",
    nameCn: "可可小姐",
    family: "柑橘玫瑰广藿调",
    notes: ["橙子", "玫瑰", "茉莉", "广藿香", "香根草"],
    palette: ["#f4c8b7", "#f7eee7", "#b98772", "#402722"],
    motifs: ["orange", "rose", "suit", "city"],
    tempo: 92,
    tags: ["职场", "优雅", "扩香", "约会", "经典"],
    occasions: ["work", "date", "formal"],
    intensity: "中高",
    gender: "女香",
    link: "https://www.chanel.com/us/fragrance/",
    description: "明亮柑橘花香落到广藿香，干练、女性化、有辨识度。"
  },
  {
    id: "chanel-bleu",
    brand: "Chanel",
    brandCn: "香奈儿",
    name: "Bleu de Chanel",
    nameCn: "蔚蓝",
    family: "柑橘木质芳香调",
    notes: ["葡萄柚", "柠檬", "焚香", "雪松", "檀木"],
    palette: ["#0d2a48", "#3f75a5", "#d7e7f5", "#09131d"],
    motifs: ["blue", "citrus", "smoke", "wood"],
    tempo: 84,
    tags: ["男香", "干净", "商务", "安全牌", "四季"],
    occasions: ["work", "date", "formal"],
    intensity: "中",
    gender: "偏男香",
    link: "https://www.chanel.com/us/fragrance/",
    description: "干净、木质、带一点烟熏感，是很稳的男香选择。"
  },
  {
    id: "dior-sauvage",
    brand: "Dior",
    brandCn: "迪奥",
    name: "Sauvage Eau de Parfum",
    nameCn: "旷野",
    family: "柑橘香草辛香调",
    notes: ["卡拉布里亚佛手柑", "胡椒", "薰衣草", "香草", "琥珀木"],
    palette: ["#0c1f3a", "#315a8a", "#d6dce8", "#050812"],
    motifs: ["desert", "blue-hour", "pepper", "vanilla"],
    tempo: 82,
    tags: ["男香", "扩香", "夜晚", "成熟", "高存在感"],
    occasions: ["date", "night", "formal"],
    intensity: "高",
    gender: "偏男香",
    link: "https://www.dior.com/en_us/beauty/products/sauvage-eau-de-parfum-E000000376.html",
    description: "清冷柑橘和香草辛香的强存在感，适合想要明显气场的人。"
  },
  {
    id: "dior-jadore",
    brand: "Dior",
    brandCn: "迪奥",
    name: "J'adore Eau de Parfum",
    nameCn: "真我",
    family: "白花花束调",
    notes: ["依兰", "大马士革玫瑰", "茉莉", "晚香玉", "花束"],
    palette: ["#f7d36a", "#fff3c5", "#f4e3a1", "#4a3313"],
    motifs: ["gold", "jasmine", "flower", "couture"],
    tempo: 78,
    tags: ["花香", "优雅", "礼物", "女性", "经典"],
    occasions: ["gift", "date", "formal"],
    intensity: "中",
    gender: "女香",
    link: "https://www.dior.com/en_us/beauty/products/j%E2%80%99adore-eau-de-parfum-Y0998031.html",
    description: "明亮饱满的花束感，华丽、女性化，很适合作为礼物。"
  },
  {
    id: "dior-miss-dior",
    brand: "Dior",
    brandCn: "迪奥",
    name: "Miss Dior Eau de Parfum",
    nameCn: "迪奥小姐",
    family: "玫瑰花束木质调",
    notes: ["千叶玫瑰", "铃兰", "牡丹", "鸢尾", "柔木"],
    palette: ["#f6b5c8", "#fff0f4", "#d87b9c", "#eee3d8"],
    motifs: ["bow", "rose", "couture", "pink"],
    tempo: 86,
    tags: ["玫瑰", "甜美", "浪漫", "礼物", "约会"],
    occasions: ["date", "gift", "daily"],
    intensity: "中",
    gender: "女香",
    link: "https://www.dior.com/en_us/beauty/products/miss-dior-eau-de-parfum-Y0996347.html",
    description: "玫瑰花束和柔木基底，浪漫、明亮，适合约会和送礼。"
  },
  {
    id: "ysl-libre",
    brand: "YSL",
    brandCn: "圣罗兰",
    name: "Libre Eau de Parfum",
    nameCn: "自由之水",
    family: "薰衣草橙花香草调",
    notes: ["薰衣草", "橙花", "茉莉", "香草", "麝香"],
    palette: ["#d8a34a", "#101010", "#f7efe2", "#c05d40"],
    motifs: ["gold", "lavender", "orange-blossom", "freedom"],
    tempo: 96,
    tags: ["酷飒", "花香", "香草", "约会", "职场"],
    occasions: ["work", "date", "party"],
    intensity: "中高",
    gender: "女香",
    link: "https://www.yslbeauty.com/int/fragrance/fragrance-for-her/libre/libre-eau-de-parfum/WW-50424YSL.html",
    description: "薰衣草和橙花的冷暖对比，适合想要独立、利落、有女人味的人。"
  },
  {
    id: "ysl-black-opium",
    brand: "YSL",
    brandCn: "圣罗兰",
    name: "Black Opium Eau de Parfum",
    nameCn: "黑鸦片",
    family: "咖啡香草白花调",
    notes: ["咖啡", "香草", "橙花", "茉莉", "广藿香"],
    palette: ["#171114", "#e05a8a", "#f5c0d5", "#050405"],
    motifs: ["coffee", "neon", "night", "vanilla"],
    tempo: 108,
    tags: ["甜", "夜晚", "派对", "性感", "高存在感"],
    occasions: ["party", "night", "date"],
    intensity: "高",
    gender: "女香",
    link: "https://www.yslbeautyus.com/fragrance/womens-fragrances/black-opium/black-opium-eau-de-parfum-spray/252YSL.html",
    description: "咖啡与香草的甜暗夜气味，适合夜晚、派对和强存在感。"
  },
  {
    id: "ysl-myslf",
    brand: "YSL",
    brandCn: "圣罗兰",
    name: "MYSLF Eau de Parfum",
    nameCn: "MYSLF",
    family: "木质花香麝香调",
    notes: ["佛手柑", "橙花", "广藿香", "木质", "麝香"],
    palette: ["#101010", "#dfe2df", "#6f7471", "#f7f7f2"],
    motifs: ["mirror", "skin", "black", "orange-blossom"],
    tempo: 82,
    tags: ["男香", "干净", "现代", "通勤", "安全牌"],
    occasions: ["work", "daily", "date"],
    intensity: "中",
    gender: "偏男香",
    link: "https://www.yslbeauty.com/int/fragrance/masculine-fragrance/myslf/myslf-eau-de-parfum/3614273852807.html",
    description: "现代干净的木质花香男香，适合日常和职场。"
  },
  {
    id: "frederic-portrait",
    brand: "Frederic Malle",
    brandCn: "馥马尔",
    name: "Portrait of a Lady",
    nameCn: "一轮玫瑰",
    family: "玫瑰广藿焚香调",
    notes: ["玫瑰", "广藿香", "黑醋栗", "焚香", "檀木"],
    palette: ["#6b0f1a", "#c43d4b", "#2c1619", "#e2b4a0"],
    motifs: ["rose", "velvet", "incense", "portrait"],
    tempo: 70,
    tags: ["玫瑰", "浓郁", "气场", "正式", "秋冬"],
    occasions: ["formal", "night", "date"],
    intensity: "高",
    gender: "中性",
    link: "https://www.fredericmalle.com/",
    description: "浓郁玫瑰、广藿和焚香，气场很强，适合成熟和正式场合。"
  },
  {
    id: "frederic-carnal",
    brand: "Frederic Malle",
    brandCn: "馥马尔",
    name: "Carnal Flower",
    nameCn: "肉欲之花",
    family: "晚香玉白花调",
    notes: ["晚香玉", "白麝香", "椰子", "桉树", "橙花"],
    palette: ["#e7fff2", "#78b887", "#ffffff", "#1c3b2b"],
    motifs: ["tuberose", "greenhouse", "white-flower", "leaf"],
    tempo: 74,
    tags: ["白花", "浓郁", "高级", "女性", "夜晚"],
    occasions: ["date", "night", "formal"],
    intensity: "高",
    gender: "女香",
    link: "https://www.fredericmalle.com/",
    description: "高浓度晚香玉和绿意，漂亮但很有存在感。"
  },
  {
    id: "frederic-musc",
    brand: "Frederic Malle",
    brandCn: "馥马尔",
    name: "Musc Ravageur",
    nameCn: "狂野麝香",
    family: "麝香琥珀香草调",
    notes: ["麝香", "琥珀", "香草", "肉桂", "丁香"],
    palette: ["#5a2b1f", "#d59c6b", "#28130f", "#f1d1a7"],
    motifs: ["amber", "musk", "spice", "warmth"],
    tempo: 66,
    tags: ["暖", "性感", "辛香", "秋冬", "夜晚"],
    occasions: ["night", "date", "winter"],
    intensity: "高",
    gender: "中性",
    link: "https://www.fredericmalle.com/product/19567/136240/samples/musc-ravageur/by-maurice-roucel",
    description: "温暖麝香、琥珀和香草辛香，适合夜晚和亲密距离。"
  },
  {
    id: "jomalone-pear",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    name: "English Pear & Freesia",
    nameCn: "英国梨与小苍兰",
    family: "果香花香调",
    notes: ["英国梨", "小苍兰", "玫瑰", "广藿香", "琥珀"],
    palette: ["#d6d87a", "#f6e6a7", "#fff9df", "#8a8f45"],
    motifs: ["pear", "freesia", "orchard", "sun"],
    tempo: 92,
    tags: ["清甜", "日常", "少女感", "礼物", "春夏"],
    occasions: ["daily", "gift", "spring"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.jomalone.com/product/25946/12553/colognes/english-pear-freesia-cologne",
    description: "清甜梨子和小苍兰，友好、轻松，很适合入门和送礼。"
  },
  {
    id: "jomalone-wood-sage",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    name: "Wood Sage & Sea Salt",
    nameCn: "鼠尾草与海盐",
    family: "海盐草本木质调",
    notes: ["海盐", "鼠尾草", "葡萄柚", "海风", "麝香"],
    palette: ["#b7c8bc", "#6d817d", "#e8e4d7", "#304340"],
    motifs: ["sea", "salt", "sage", "cliff"],
    tempo: 78,
    tags: ["海风", "中性", "清冷", "通勤", "春夏"],
    occasions: ["daily", "work", "summer"],
    intensity: "轻",
    gender: "中性",
    link: "https://www.jomalone.com/products/25946/colognes",
    description: "咸咸的海风和草本木质，干净、不甜、非常日常。"
  },
  {
    id: "jomalone-peony",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    name: "Peony & Blush Suede",
    nameCn: "牡丹与胭红麂绒",
    family: "牡丹果香麂皮调",
    notes: ["牡丹", "红苹果", "茉莉", "玫瑰", "麂皮"],
    palette: ["#f3a4b8", "#f7dce4", "#a75b68", "#fff6f7"],
    motifs: ["peony", "suede", "apple", "blush"],
    tempo: 88,
    tags: ["花香", "甜美", "约会", "礼物", "女性"],
    occasions: ["date", "gift", "daily"],
    intensity: "轻中",
    gender: "女香",
    link: "https://www.jomalone.com/products/25946/colognes",
    description: "牡丹、红苹果和柔软麂皮，甜美但不厚重。"
  },
  {
    id: "lelabo-santal33",
    brand: "Le Labo",
    brandCn: "Le Labo",
    name: "Santal 33",
    nameCn: "檀香 33",
    family: "檀香皮革木质调",
    notes: ["檀香", "豆蔻", "紫罗兰", "纸莎草", "皮革"],
    palette: ["#b99b70", "#e3d2b1", "#3a2d24", "#6f5a43"],
    motifs: ["sandalwood", "leather", "paper", "desert"],
    tempo: 68,
    tags: ["木质", "中性", "标志性", "秋冬", "个性"],
    occasions: ["daily", "work", "travel"],
    intensity: "中高",
    gender: "中性",
    link: "https://www.lelabofragrances.com/classic-collection.html",
    description: "檀香、皮革和纸感木质，辨识度高，适合喜欢中性木质的人。"
  },
  {
    id: "lelabo-another13",
    brand: "Le Labo",
    brandCn: "Le Labo",
    name: "Another 13",
    nameCn: "别物 13",
    family: "龙涎麝香皮肤调",
    notes: ["龙涎香调", "麝香", "梨", "茉莉", "苔藓"],
    palette: ["#e6e0d2", "#b6b1a6", "#ffffff", "#46433e"],
    motifs: ["skin", "paper", "musk", "minimal"],
    tempo: 62,
    tags: ["伪体香", "极简", "干净", "通勤", "亲肤"],
    occasions: ["daily", "work", "clean"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.lelabofragrances.com/classic-collection.html",
    description: "皮肤感麝香和干净纸感，适合喜欢低调但有质感的人。"
  },
  {
    id: "lelabo-thenoir29",
    brand: "Le Labo",
    brandCn: "Le Labo",
    name: "The Noir 29",
    nameCn: "黑茶 29",
    family: "茶香烟草木质调",
    notes: ["红茶", "无花果", "烟草", "雪松", "干草"],
    palette: ["#3c2f24", "#a27547", "#d7c0a0", "#17110d"],
    motifs: ["tea", "fig", "tobacco", "wood"],
    tempo: 72,
    tags: ["茶香", "木质", "成熟", "秋冬", "文艺"],
    occasions: ["work", "night", "quiet"],
    intensity: "中",
    gender: "中性",
    link: "https://www.lelabofragrances.com/classic-collection.html",
    description: "茶、无花果、烟草和木质，适合喜欢成熟文艺感的人。"
  },
  {
    id: "margiela-jazz",
    brand: "Maison Margiela",
    brandCn: "马吉拉",
    name: "Replica Jazz Club",
    nameCn: "爵士俱乐部",
    family: "朗姆烟草香草调",
    notes: ["粉红胡椒", "朗姆", "烟草叶", "香草", "安息香"],
    palette: ["#4a2218", "#c07a45", "#110b09", "#f0c28a"],
    motifs: ["jazz", "rum", "tobacco", "club"],
    tempo: 92,
    tags: ["夜晚", "烟草", "酒感", "约会", "秋冬"],
    occasions: ["night", "date", "party"],
    intensity: "中高",
    gender: "中性",
    link: "https://www.maisonmargiela-fragrances.us/fragrances/replica-jazz-club/3614273744713.html",
    description: "朗姆、烟草和香草的夜晚气味，像微暗灯光下的爵士酒吧。"
  },
  {
    id: "margiela-lazy",
    brand: "Maison Margiela",
    brandCn: "马吉拉",
    name: "Replica Lazy Sunday Morning",
    nameCn: "慵懒周日早晨",
    family: "皂感白花麝香调",
    notes: ["梨", "铃兰", "鸢尾", "玫瑰", "白麝香"],
    palette: ["#ffffff", "#e9e3d9", "#c8d1cf", "#f7f2ec"],
    motifs: ["linen", "morning", "soap", "window"],
    tempo: 66,
    tags: ["干净", "皂感", "亲肤", "日常", "通勤"],
    occasions: ["daily", "clean", "work"],
    intensity: "轻",
    gender: "中性",
    link: "https://www.maisonmargiela.com/en-us/replica-lazy-sunday-morning-eau-de-toilette-S33YX0018S10932001.html",
    description: "干净床单和白麝香的气味，适合想要舒服、自然、亲肤的人。"
  },
  {
    id: "margiela-fireplace",
    brand: "Maison Margiela",
    brandCn: "马吉拉",
    name: "Replica By the Fireplace",
    nameCn: "壁炉火光",
    family: "烟熏栗子香草调",
    notes: ["粉红胡椒", "橙花", "栗子", "愈创木", "香草"],
    palette: ["#6f2f16", "#e6a35c", "#20100a", "#ffcf83"],
    motifs: ["fireplace", "chestnut", "smoke", "winter"],
    tempo: 60,
    tags: ["烟熏", "暖", "甜", "秋冬", "夜晚"],
    occasions: ["winter", "night", "date"],
    intensity: "中高",
    gender: "中性",
    link: "https://www.maisonmargiela-fragrances.us/fragrances/refillable-bottles/",
    description: "烟熏木头、烤栗子和香草，像冬天壁炉边的暖意。"
  }
];

PERFUME_CATALOG.push(
  {
    id: "tomford-oudwood",
    brand: "Tom Ford",
    brandCn: "汤姆福特",
    name: "Oud Wood",
    nameCn: "乌木沉香",
    family: "乌木豆蔻檀香调",
    notes: ["乌木", "豆蔻", "檀香", "香根草", "琥珀"],
    palette: ["#3a231b", "#9a6a4b", "#d6b38a", "#15100d"],
    motifs: ["oud", "wood", "spice", "amber"],
    tempo: 66,
    tags: ["木质", "沉稳", "高级", "秋冬", "商务"],
    occasions: ["work", "formal", "night"],
    intensity: "中高",
    gender: "中性",
    link: "https://www.tomfordbeauty.com/product/oud-wood-eau-de-parfum",
    description: "干净克制的乌木与豆蔻辛香，适合想要稳重高级木质感的人。"
  },
  {
    id: "mfk-br540",
    brand: "Maison Francis Kurkdjian",
    brandCn: "MFK",
    name: "Baccarat Rouge 540",
    nameCn: "水晶之焰",
    family: "琥珀木质甜香调",
    notes: ["藏红花", "茉莉", "龙涎香调", "雪松", "冷甜感"],
    palette: ["#b31f2d", "#f4d2b0", "#ffffff", "#5f1018"],
    motifs: ["crystal", "amber", "saffron", "glow"],
    tempo: 90,
    tags: ["甜", "扩香", "高级", "社交", "高存在感"],
    occasions: ["party", "date", "formal"],
    intensity: "高",
    gender: "中性",
    link: "https://www.franciskurkdjian.com/us-en/p/baccarat-rouge-540-eau-de-parfum-RA12232.html",
    description: "透明甜感、琥珀木质和强扩散，很适合需要记忆点的场合。"
  },
  {
    id: "kilian-love",
    brand: "Kilian",
    brandCn: "凯利安",
    name: "Love, Don't Be Shy",
    nameCn: "羞涩之爱",
    family: "橙花棉花糖美食调",
    notes: ["橙花", "棉花糖", "香草", "焦糖", "白花"],
    palette: ["#f6a0aa", "#ffe1d0", "#d36b6f", "#fff3e7"],
    motifs: ["marshmallow", "orange-blossom", "kiss", "sugar"],
    tempo: 104,
    tags: ["甜", "约会", "美食调", "女性", "夜晚"],
    occasions: ["date", "party", "gift"],
    intensity: "高",
    gender: "女香",
    link: "https://www.bykilian.com/product/19797/50771/perfume/love-dont-be-shy/the-narcotics",
    description: "甜蜜橙花和棉花糖，适合喜欢高甜约会香的人。"
  },
  {
    id: "creed-aventus",
    brand: "Creed",
    brandCn: "信仰",
    name: "Aventus",
    nameCn: "拿破仑之水",
    family: "果香烟熏木质调",
    notes: ["菠萝", "佛手柑", "桦木", "麝香", "橡木苔"],
    palette: ["#111111", "#d3b56b", "#9fb0a0", "#f1efe3"],
    motifs: ["pineapple", "smoke", "oakmoss", "crown"],
    tempo: 92,
    tags: ["男香", "果香", "烟熏", "商务", "气场"],
    occasions: ["work", "formal", "date"],
    intensity: "中高",
    gender: "偏男香",
    link: "https://www.creedfragrances.com/mens-fragrances/aventus",
    description: "果香、烟熏和木质结合，适合成熟、有气场的男香方向。"
  },
  {
    id: "guerlain-mon",
    brand: "Guerlain",
    brandCn: "娇兰",
    name: "Mon Guerlain",
    nameCn: "我的娇兰",
    family: "薰衣草香草东方调",
    notes: ["薰衣草", "茉莉", "香草", "檀香", "鸢尾"],
    palette: ["#caa3c8", "#f7e7ef", "#8f6f91", "#f2d0b0"],
    motifs: ["lavender", "vanilla", "ribbon", "soft"],
    tempo: 76,
    tags: ["温柔", "香草", "女性", "约会", "礼物"],
    occasions: ["date", "gift", "daily"],
    intensity: "中",
    gender: "女香",
    link: "https://www.guerlain.com/us/en-us/fragrance/womens-fragrances/mon-guerlain/",
    description: "薰衣草和香草的温柔东方调，适合柔和、亲近的女性气质。"
  },
  {
    id: "prada-paradoxe",
    brand: "Prada",
    brandCn: "普拉达",
    name: "Paradoxe",
    nameCn: "我本莫测",
    family: "橙花琥珀麝香调",
    notes: ["橙花", "茉莉", "琥珀", "麝香", "梨"],
    palette: ["#f49a8a", "#ffe4dc", "#171717", "#f6f1ea"],
    motifs: ["triangle", "orange-blossom", "skin", "amber"],
    tempo: 90,
    tags: ["现代", "花香", "甜", "职场", "约会"],
    occasions: ["work", "date", "daily"],
    intensity: "中",
    gender: "女香",
    link: "https://www.prada-beauty.com/fragrance/womens-fragrances/prada-paradoxe/",
    description: "现代花香和琥珀麝香，甜度适中，适合通勤和约会。"
  },
  {
    id: "gucci-bloom",
    brand: "Gucci",
    brandCn: "古驰",
    name: "Bloom",
    nameCn: "繁花",
    family: "白花晚香玉茉莉调",
    notes: ["晚香玉", "茉莉", "使君子", "白花", "绿意"],
    palette: ["#f4b7b0", "#fff0ec", "#b84649", "#3f6b4c"],
    motifs: ["bloom", "tuberose", "garden", "pink"],
    tempo: 78,
    tags: ["白花", "女性", "温柔", "春夏", "约会"],
    occasions: ["date", "daily", "spring"],
    intensity: "中",
    gender: "女香",
    link: "https://www.gucci.com/us/en/ca/beauty/fragrances/fragrances-for-women-c-beauty-fragrances-for-women",
    description: "白花庭院感，适合喜欢自然花香和温柔女性气质的人。"
  },
  {
    id: "valentino-born-roma",
    brand: "Valentino",
    brandCn: "华伦天奴",
    name: "Donna Born in Roma",
    nameCn: "罗马女士",
    family: "黑加仑茉莉香草调",
    notes: ["黑加仑", "茉莉", "波旁香草", "木质", "粉红胡椒"],
    palette: ["#f5a1b8", "#111111", "#ffdee9", "#bb4160"],
    motifs: ["roma", "stud", "jasmine", "vanilla"],
    tempo: 100,
    tags: ["甜", "年轻", "约会", "社交", "女性"],
    occasions: ["date", "party", "daily"],
    intensity: "中高",
    gender: "女香",
    link: "https://www.valentino-beauty.us/fragrance/womens-fragrances/donna-born-in-roma/",
    description: "黑加仑、茉莉和香草的甜美社交香，适合年轻明亮的风格。"
  },
  {
    id: "armani-si",
    brand: "Armani",
    brandCn: "阿玛尼",
    name: "Si Eau de Parfum",
    nameCn: "挚爱",
    family: "黑加仑玫瑰香草调",
    notes: ["黑加仑", "玫瑰", "小苍兰", "香草", "广藿香"],
    palette: ["#8d2f3d", "#e5b7b8", "#1c1112", "#f7e1d8"],
    motifs: ["rose", "blackcurrant", "velvet", "signature"],
    tempo: 82,
    tags: ["优雅", "玫瑰", "成熟", "职场", "约会"],
    occasions: ["work", "date", "formal"],
    intensity: "中",
    gender: "女香",
    link: "https://www.giorgioarmanibeauty-usa.com/fragrances/womens-fragrances/si/",
    description: "黑加仑和玫瑰带来优雅甜感，适合成熟温柔的职场和约会。"
  },
  {
    id: "lancome-lavie",
    brand: "Lancome",
    brandCn: "兰蔻",
    name: "La Vie Est Belle",
    nameCn: "美丽人生",
    family: "鸢尾果仁糖香草调",
    notes: ["鸢尾", "梨", "黑加仑", "果仁糖", "香草"],
    palette: ["#f2b6c6", "#ffe5ef", "#d88a9d", "#fff6ea"],
    motifs: ["smile", "iris", "sugar", "pink"],
    tempo: 88,
    tags: ["甜", "温暖", "礼物", "女性", "秋冬"],
    occasions: ["gift", "date", "winter"],
    intensity: "高",
    gender: "女香",
    link: "https://www.lancome-usa.com/fragrance/women-fragrances/la-vie-est-belle/",
    description: "甜美果仁糖和鸢尾香草，适合喜欢温暖甜香的人。"
  },
  {
    id: "mugler-alien",
    brand: "Mugler",
    brandCn: "穆勒",
    name: "Alien",
    nameCn: "异形",
    family: "茉莉琥珀木质调",
    notes: ["茉莉", "琥珀", "羊绒木", "白花", "暖木"],
    palette: ["#5b2a83", "#b781d9", "#f1d8ff", "#1d1028"],
    motifs: ["alien", "jasmine", "purple", "amber"],
    tempo: 76,
    tags: ["白花", "高存在感", "夜晚", "女性", "神秘"],
    occasions: ["night", "party", "date"],
    intensity: "高",
    gender: "女香",
    link: "https://www.muglerusa.com/fragrance/womens-fragrances/alien/",
    description: "茉莉、琥珀和木质的强烈存在感，适合夜晚和神秘气质。"
  },
  {
    id: "givenchy-interdit",
    brand: "Givenchy",
    brandCn: "纪梵希",
    name: "L'Interdit",
    nameCn: "禁忌",
    family: "白花广藿辛香调",
    notes: ["橙花", "茉莉", "晚香玉", "广藿香", "香根草"],
    palette: ["#111111", "#ffffff", "#d34a56", "#8a1d26"],
    motifs: ["forbidden", "white-flower", "black", "red"],
    tempo: 94,
    tags: ["白花", "酷", "夜晚", "女性", "扩香"],
    occasions: ["night", "date", "formal"],
    intensity: "中高",
    gender: "女香",
    link: "https://www.givenchybeauty.com/us/fragrance/womens-fragrance/linterdit/",
    description: "白花和暗色木质的反差，适合想要优雅但有锋利感的人。"
  },
  {
    id: "bvlgari-omnia",
    brand: "Bvlgari",
    brandCn: "宝格丽",
    name: "Omnia Crystalline",
    nameCn: "晶莹",
    family: "莲花竹子麝香调",
    notes: ["竹子", "莲花", "梨", "茶", "麝香"],
    palette: ["#e6f2f1", "#b9d8d5", "#ffffff", "#89aaa6"],
    motifs: ["crystal", "lotus", "bamboo", "water"],
    tempo: 72,
    tags: ["清透", "水感", "通勤", "亲肤", "春夏"],
    occasions: ["daily", "work", "summer"],
    intensity: "轻",
    gender: "女香",
    link: "https://www.bulgari.com/en-us/fragrances/womens",
    description: "莲花、竹子和水晶感，很适合想要清透温柔的人。"
  },
  {
    id: "acquadiparma-colonia",
    brand: "Acqua di Parma",
    brandCn: "帕尔玛之水",
    name: "Colonia",
    nameCn: "克罗尼亚",
    family: "意式柑橘芳香调",
    notes: ["柠檬", "佛手柑", "薰衣草", "迷迭香", "香根草"],
    palette: ["#f4cf3d", "#fff2a8", "#335241", "#f9f3d0"],
    motifs: ["italy", "citrus", "sun", "tailoring"],
    tempo: 96,
    tags: ["柑橘", "绅士", "清爽", "夏天", "商务"],
    occasions: ["work", "summer", "daily"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.acquadiparma.com/en-us/colonia/",
    description: "明亮意式柑橘和草本，适合夏天、白衬衫和干净绅士感。"
  },
  {
    id: "penhaligons-luna",
    brand: "Penhaligon's",
    brandCn: "潘海利根",
    name: "Luna",
    nameCn: "月亮女神",
    family: "柑橘玫瑰冷感调",
    notes: ["柠檬", "佛手柑", "玫瑰", "茉莉", "冷杉"],
    palette: ["#cfe7ef", "#f6f7ff", "#7ba9b8", "#fff9d8"],
    motifs: ["moon", "rose", "citrus", "night"],
    tempo: 84,
    tags: ["清冷", "玫瑰", "仙气", "春夏", "女性"],
    occasions: ["daily", "date", "spring"],
    intensity: "轻中",
    gender: "女香",
    link: "https://www.penhaligons.com/us/en/categories/fragrances",
    description: "清冷柑橘和柔玫瑰，适合干净、轻盈、带一点仙气的人。"
  },
  {
    id: "sergelutens-berlin",
    brand: "Serge Lutens",
    brandCn: "芦丹氏",
    name: "La Fille de Berlin",
    nameCn: "柏林少女",
    family: "玫瑰胡椒调",
    notes: ["玫瑰", "胡椒", "蜂蜜", "麝香", "金属感"],
    palette: ["#9f0f2f", "#d7495c", "#1b0a10", "#efc3c8"],
    motifs: ["rose", "metal", "berlin", "thorn"],
    tempo: 78,
    tags: ["玫瑰", "冷艳", "个性", "秋冬", "女性"],
    occasions: ["date", "night", "formal"],
    intensity: "中高",
    gender: "女香",
    link: "https://sergelutens.com/collections/fragrances",
    description: "带冷感和辛辣边缘的玫瑰，适合喜欢个性玫瑰的人。"
  },
  {
    id: "amouage-reflection",
    brand: "Amouage",
    brandCn: "爱慕",
    name: "Reflection Man",
    nameCn: "倒影男士",
    family: "白花木质皂感调",
    notes: ["橙花", "茉莉", "鸢尾", "檀香", "雪松"],
    palette: ["#f4f1e6", "#c8d0c5", "#5b665c", "#ffffff"],
    motifs: ["mirror", "white-flower", "sandalwood", "linen"],
    tempo: 72,
    tags: ["男香", "干净", "皂感", "商务", "高级"],
    occasions: ["work", "formal", "daily"],
    intensity: "中",
    gender: "偏男香",
    link: "https://www.amouage.com/us/fragrances",
    description: "白花、皂感和木质结合，适合干净高级的男士通勤。"
  },
  {
    id: "initio-sideeffect",
    brand: "Initio",
    brandCn: "Initio",
    name: "Side Effect",
    nameCn: "副作用",
    family: "朗姆烟草肉桂调",
    notes: ["朗姆", "烟草", "肉桂", "香草", "藏红花"],
    palette: ["#3a1410", "#b85b34", "#e0a06e", "#160907"],
    motifs: ["rum", "tobacco", "spice", "night"],
    tempo: 84,
    tags: ["酒感", "甜辛", "夜晚", "性感", "秋冬"],
    occasions: ["night", "date", "party"],
    intensity: "高",
    gender: "中性",
    link: "https://us.initioparfums.com/collections/the-fragrances",
    description: "朗姆、烟草和肉桂的暖甜暗夜感，适合夜晚和强氛围。"
  },
  {
    id: "pdm-delina",
    brand: "Parfums de Marly",
    brandCn: "马利之香",
    name: "Delina",
    nameCn: "黛丽娜",
    family: "荔枝玫瑰牡丹调",
    notes: ["荔枝", "大黄", "玫瑰", "牡丹", "香草"],
    palette: ["#f4a6b8", "#ffe0e8", "#c45b78", "#ffffff"],
    motifs: ["rose", "lychee", "pink", "palace"],
    tempo: 90,
    tags: ["玫瑰", "甜", "少女", "约会", "礼物"],
    occasions: ["date", "gift", "daily"],
    intensity: "中高",
    gender: "女香",
    link: "https://us.parfums-de-marly.com/collections/womens-fragrances",
    description: "荔枝玫瑰和牡丹，甜美、明亮，很适合约会和送礼。"
  },
  {
    id: "xerjoff-naxos",
    brand: "Xerjoff",
    brandCn: "Xerjoff",
    name: "Naxos",
    nameCn: "纳克索斯",
    family: "蜂蜜烟草薰衣草调",
    notes: ["薰衣草", "蜂蜜", "烟草", "香草", "肉桂"],
    palette: ["#d7a24f", "#4b2d17", "#f0d0a0", "#1a0f09"],
    motifs: ["honey", "tobacco", "sicily", "lavender"],
    tempo: 76,
    tags: ["蜂蜜", "烟草", "暖", "秋冬", "中性"],
    occasions: ["date", "night", "winter"],
    intensity: "高",
    gender: "中性",
    link: "https://xerjoff.com/usa/17-fragrances",
    description: "蜂蜜烟草和薰衣草的温暖组合，适合秋冬和亲密场合。"
  },
  {
    id: "nishane-hacivat",
    brand: "Nishane",
    brandCn: "Nishane",
    name: "Hacivat",
    nameCn: "哈西瓦特",
    family: "菠萝橡木苔木质调",
    notes: ["菠萝", "葡萄柚", "雪松", "橡木苔", "广藿香"],
    palette: ["#bcc55c", "#f2df85", "#485637", "#14180f"],
    motifs: ["pineapple", "oakmoss", "shadow", "green"],
    tempo: 88,
    tags: ["果香", "木质", "扩香", "商务", "中性"],
    occasions: ["work", "formal", "daily"],
    intensity: "高",
    gender: "中性",
    link: "https://nishane.com/product/hacivat/",
    description: "菠萝果香和橡木苔木质，存在感强，适合想要干练气场的人。"
  },
  {
    id: "exnihilo-fleur",
    brand: "Ex Nihilo",
    brandCn: "Ex Nihilo",
    name: "Fleur Narcotique",
    nameCn: "麻醉花",
    family: "荔枝牡丹白花调",
    notes: ["荔枝", "桃子", "牡丹", "橙花", "麝香"],
    palette: ["#f7b5c8", "#ffe8ef", "#d77993", "#ffffff"],
    motifs: ["peony", "lychee", "narcotic", "musk"],
    tempo: 92,
    tags: ["花果香", "少女", "社交", "约会", "女性"],
    occasions: ["date", "party", "daily"],
    intensity: "中",
    gender: "女香",
    link: "https://www.ex-nihilo-paris.com/shop/fragrances/",
    description: "荔枝、牡丹和麝香的明亮花果香，适合社交和约会。"
  },
  {
    id: "aesop-tacit",
    brand: "Aesop",
    brandCn: "伊索",
    name: "Tacit",
    nameCn: "悟",
    family: "柑橘罗勒草本调",
    notes: ["柚子", "罗勒", "香根草", "丁香", "青草"],
    palette: ["#d7d782", "#60724e", "#f1edcf", "#2f3b29"],
    motifs: ["yuzu", "basil", "green", "minimal"],
    tempo: 86,
    tags: ["草本", "清爽", "极简", "通勤", "夏天"],
    occasions: ["daily", "work", "summer"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.aesop.com/us/c/fragrance/",
    description: "柚子和罗勒的清爽草本，适合喜欢极简清冷气质的人。"
  },
  {
    id: "loewe-001",
    brand: "Loewe",
    brandCn: "罗意威",
    name: "001 Woman",
    nameCn: "事后清晨女香",
    family: "柑橘檀木香草调",
    notes: ["柑橘", "茉莉", "檀香", "香草", "麝香"],
    palette: ["#efe0c5", "#b99c75", "#ffffff", "#5d4a38"],
    motifs: ["morning", "skin", "sandalwood", "linen"],
    tempo: 70,
    tags: ["亲肤", "温柔", "木质", "约会", "日常"],
    occasions: ["date", "daily", "clean"],
    intensity: "轻中",
    gender: "女香",
    link: "https://www.loewe.com/usa/en/loewe-perfumes/",
    description: "檀木、香草和亲肤麝香，温柔、贴近、适合日常约会。"
  },
  {
    id: "celine-blacktie",
    brand: "Celine",
    brandCn: "思琳",
    name: "Black Tie",
    nameCn: "黑领结",
    family: "香草鸢尾雪松调",
    notes: ["香草", "鸢尾", "雪松", "白麝香", "树苔"],
    palette: ["#111111", "#e7ddcc", "#8c7b68", "#ffffff"],
    motifs: ["black-tie", "vanilla", "iris", "tailoring"],
    tempo: 64,
    tags: ["香草", "优雅", "中性", "正式", "夜晚"],
    occasions: ["formal", "night", "date"],
    intensity: "中",
    gender: "中性",
    link: "https://www.celine.com/en-us/celine-haute-parfumerie/",
    description: "克制的香草鸢尾和雪松，像黑色正装，优雅但不甜腻。"
  },
  {
    id: "lv-imagination",
    brand: "Louis Vuitton",
    brandCn: "路易威登",
    name: "Imagination",
    nameCn: "想象力",
    family: "柑橘茶香龙涎调",
    notes: ["香橼", "佛手柑", "红茶", "肉桂", "龙涎香调"],
    palette: ["#9fd7e8", "#f7e38c", "#ffffff", "#224f67"],
    motifs: ["citrus", "tea", "sky", "travel"],
    tempo: 94,
    tags: ["清爽", "茶香", "高级", "男香", "夏天"],
    occasions: ["daily", "work", "summer"],
    intensity: "中",
    gender: "偏男香",
    link: "https://us.louisvuitton.com/eng-us/men/accessories/fragrances/_/N-t1r0yp",
    description: "柑橘、茶和干净龙涎感，适合夏天和干净高级男香方向。"
  },
  {
    id: "matiere-parisianmusc",
    brand: "Matiere Premiere",
    brandCn: "首要之香",
    name: "Parisian Musc",
    nameCn: "巴黎麝香",
    family: "无花果木质麝香调",
    notes: ["麝香", "无花果叶", "雪松", "黄葵籽", "木质"],
    palette: ["#dcd7c8", "#a8ad8d", "#ffffff", "#5f6752"],
    motifs: ["musk", "fig-leaf", "paris", "skin"],
    tempo: 68,
    tags: ["麝香", "绿意", "亲肤", "通勤", "中性"],
    occasions: ["daily", "work", "clean"],
    intensity: "轻中",
    gender: "中性",
    link: "https://matiere-premiere.com/en-us/collections/perfumes",
    description: "绿意无花果叶和亲肤麝香，低调、干净、适合通勤。"
  },
  {
    id: "bdk-grischarnel",
    brand: "BDK Parfums",
    brandCn: "BDK",
    name: "Gris Charnel",
    nameCn: "肉欲灰",
    family: "茶香无花果檀木调",
    notes: ["无花果", "红茶", "豆蔻", "鸢尾", "檀香"],
    palette: ["#77716c", "#d8c7b5", "#302b27", "#f0e5d7"],
    motifs: ["tea", "fig", "grey", "sandalwood"],
    tempo: 72,
    tags: ["茶香", "木质", "温柔", "秋冬", "中性"],
    occasions: ["date", "work", "night"],
    intensity: "中",
    gender: "中性",
    link: "https://bdkparfums.com/us_en/fragrances/",
    description: "茶、无花果和檀木，温柔又有灰调质感，适合秋冬。"
  },
  {
    id: "dsdurga-radio",
    brand: "D.S. & Durga",
    brandCn: "D.S. & Durga",
    name: "Radio Bombay",
    nameCn: "孟买电台",
    family: "檀香椰奶木质调",
    notes: ["檀香", "雪松", "椰奶", "鸢尾", "琥珀"],
    palette: ["#8f633d", "#e6c79c", "#33251b", "#f1e4ce"],
    motifs: ["radio", "sandalwood", "heat", "coconut"],
    tempo: 74,
    tags: ["檀香", "温暖", "个性", "中性", "秋冬"],
    occasions: ["daily", "travel", "night"],
    intensity: "中",
    gender: "中性",
    link: "https://www.dsanddurga.com/collections/fragrance",
    description: "温暖檀香和椰奶感，带一点异域和旧电台画面。"
  },
  {
    id: "zoologist-bee",
    brand: "Zoologist",
    brandCn: "动物学家",
    name: "Bee",
    nameCn: "蜜蜂",
    family: "蜂蜜花粉树脂调",
    notes: ["蜂蜜", "蜂蜡", "橙花", "香草", "安息香"],
    palette: ["#f2b52e", "#5a3414", "#fff0a6", "#211307"],
    motifs: ["bee", "honey", "wax", "flower"],
    tempo: 78,
    tags: ["蜂蜜", "甜", "个性", "秋冬", "高存在感"],
    occasions: ["night", "winter", "gift"],
    intensity: "高",
    gender: "中性",
    link: "https://www.zoologistperfumes.com/collections/perfumes",
    description: "蜂蜜、蜂蜡和树脂的浓郁甜暖感，适合喜欢个性美食调的人。"
  },
  {
    id: "millerharris-tea",
    brand: "Miller Harris",
    brandCn: "米勒海莉诗",
    name: "Tea Tonique",
    nameCn: "茶香补剂",
    family: "茶香柑橘烟草调",
    notes: ["佛手柑", "红茶", "烟草", "马黛茶", "麝香"],
    palette: ["#b58a4d", "#e7d0a1", "#384436", "#18150f"],
    motifs: ["tea", "steam", "citrus", "tobacco"],
    tempo: 82,
    tags: ["茶香", "清爽", "中性", "通勤", "文艺"],
    occasions: ["daily", "work", "spring"],
    intensity: "中",
    gender: "中性",
    link: "https://www.millerharris.com/collections/fragrance",
    description: "红茶和柑橘带一点烟草，非常适合喜欢茶香和文艺感的人。"
  },
  {
    id: "floraiku-umbrella",
    brand: "Floraiku",
    brandCn: "俳句之香",
    name: "One Umbrella for Two",
    nameCn: "一伞两人",
    family: "黑加仑茶香米香调",
    notes: ["黑加仑", "玄米茶", "雪松", "米香", "果香"],
    palette: ["#6e1f34", "#d8b27a", "#f3e4c7", "#1e1713"],
    motifs: ["umbrella", "tea", "berry", "rain"],
    tempo: 80,
    tags: ["果香", "茶香", "温柔", "约会", "小众"],
    occasions: ["date", "daily", "rain"],
    intensity: "中",
    gender: "中性",
    link: "https://www.floraiku.com/us/fragrances/",
    description: "黑加仑和玄米茶的温柔组合，适合雨天和暧昧氛围。"
  },
  {
    id: "cdg-wonderwood",
    brand: "Comme des Garcons",
    brandCn: "川久保玲",
    name: "Wonderwood",
    nameCn: "奇迹木",
    family: "多重木质辛香调",
    notes: ["雪松", "檀香", "愈创木", "香根草", "胡椒"],
    palette: ["#4b3324", "#a0734f", "#211712", "#d0b08b"],
    motifs: ["wood", "forest", "pepper", "dark"],
    tempo: 70,
    tags: ["木质", "个性", "中性", "秋冬", "冷感"],
    occasions: ["work", "night", "travel"],
    intensity: "中高",
    gender: "中性",
    link: "https://www.comme-des-garcons-parfum.com/perfumes/",
    description: "非常木质、干燥、带一点辛香，适合喜欢非甜木质的人。"
  },
  {
    id: "lap-artisan-figuier",
    brand: "L'Artisan Parfumeur",
    brandCn: "阿蒂仙",
    name: "Premier Figuier",
    nameCn: "无花果树",
    family: "无花果叶椰奶木质调",
    notes: ["无花果叶", "无花果", "椰奶", "檀木", "绿叶"],
    palette: ["#7f9963", "#e4d7ab", "#50613d", "#fff3d3"],
    motifs: ["fig", "leaf", "milk", "tree"],
    tempo: 78,
    tags: ["无花果", "绿意", "奶感", "春夏", "自然"],
    occasions: ["daily", "summer", "travel"],
    intensity: "轻中",
    gender: "中性",
    link: "https://www.artisanparfumeur.com/fragrance.html",
    description: "无花果叶和奶感木质，很适合春夏自然气质。"
  },
  {
    id: "eldo-you",
    brand: "Etat Libre d'Orange",
    brandCn: "解放橘郡",
    name: "You or Someone Like You",
    nameCn: "你或像你的人",
    family: "薄荷柑橘玫瑰调",
    notes: ["薄荷", "葡萄柚", "佛手柑", "玫瑰", "绿叶"],
    palette: ["#95d680", "#f5f1c8", "#4f8f5a", "#ffffff"],
    motifs: ["mint", "sun", "green", "california"],
    tempo: 96,
    tags: ["薄荷", "清新", "夏天", "中性", "活力"],
    occasions: ["summer", "daily", "sport"],
    intensity: "轻中",
    gender: "中性",
    link: "https://us.etatlibredorange.com/collections/fragrances",
    description: "薄荷、柑橘和绿意，很适合热天和想要轻盈活力的人。"
  },
  {
    id: "tauer-desert",
    brand: "Tauer",
    brandCn: "陶尔",
    name: "L'Air du Desert Marocain",
    nameCn: "摩洛哥沙漠空气",
    family: "琥珀辛香树脂调",
    notes: ["芫荽", "孜然", "岩玫瑰", "琥珀", "雪松"],
    palette: ["#b56f37", "#e2b06c", "#5b321b", "#1c120d"],
    motifs: ["desert", "amber", "spice", "wind"],
    tempo: 62,
    tags: ["辛香", "琥珀", "干燥", "小众", "秋冬"],
    occasions: ["night", "winter", "travel"],
    intensity: "高",
    gender: "中性",
    link: "https://tauerperfumes.com/",
    description: "干燥沙漠风、香料和琥珀树脂，适合非常小众的成熟气质。"
  },
  {
    id: "essential-bois",
    brand: "Essential Parfums",
    brandCn: "Essential Parfums",
    name: "Bois Imperial",
    nameCn: "帝国之木",
    family: "罗勒木质辛香调",
    notes: ["罗勒", "花椒", "香根草", "木质", "龙涎香调"],
    palette: ["#64705d", "#d4d0b5", "#2f382d", "#8a9276"],
    motifs: ["wood", "basil", "pepper", "minimal"],
    tempo: 82,
    tags: ["木质", "清冷", "性价比", "通勤", "中性"],
    occasions: ["work", "daily", "spring"],
    intensity: "中",
    gender: "中性",
    link: "https://us.essentialparfums.com/collections/fragrances",
    description: "清冷木质和罗勒辛香，适合日常通勤和中性风。"
  },
  {
    id: "juliette-not",
    brand: "Juliette Has a Gun",
    brandCn: "佩枪朱丽叶",
    name: "Not a Perfume",
    nameCn: "非香水",
    family: "龙涎麝香单体调",
    notes: ["龙涎香调", "麝香", "皮肤感", "干净", "极简"],
    palette: ["#f5f3ed", "#ffffff", "#c7c4bd", "#141414"],
    motifs: ["skin", "minimal", "molecule", "white"],
    tempo: 60,
    tags: ["伪体香", "极简", "干净", "通勤", "亲肤"],
    occasions: ["daily", "work", "clean"],
    intensity: "轻",
    gender: "中性",
    link: "https://www.juliettehasagun.com/en/fragrances",
    description: "极简皮肤感麝香，适合不想像喷了香水但想闻起来干净的人。"
  },
  {
    id: "clean-skin",
    brand: "Clean Reserve",
    brandCn: "Clean Reserve",
    name: "Skin",
    nameCn: "肌肤",
    family: "麝香盐感亲肤调",
    notes: ["麝香", "盐感", "果仁糖", "皮肤感", "木质"],
    palette: ["#f3e6d8", "#ffffff", "#c9b5a4", "#7d6758"],
    motifs: ["skin", "salt", "soft", "clean"],
    tempo: 64,
    tags: ["亲肤", "干净", "温柔", "通勤", "伪体香"],
    occasions: ["daily", "clean", "work"],
    intensity: "轻",
    gender: "中性",
    link: "https://www.cleanbeauty.com/collections/fragrance",
    description: "柔软亲肤的麝香和一点盐感，适合日常近距离。"
  }
);

export const PERFUME_BRANDS = [...new Set(PERFUME_CATALOG.map((item) => item.brand))];

export function buildPerfumeMap() {
  return Object.fromEntries(PERFUME_CATALOG.map((item) => [
    item.id,
    {
      name: `${item.brandCn} ${item.nameCn}`,
      family: item.family,
      notes: item.notes,
      palette: item.palette,
      motifs: item.motifs,
      tempo: item.tempo,
      brand: item.brand,
      brandCn: item.brandCn,
      originalName: item.name,
      nameCn: item.nameCn,
      tags: item.tags,
      occasions: item.occasions,
      intensity: item.intensity,
      gender: item.gender,
      link: item.link,
      description: item.description
    }
  ]));
}

export function getCatalogItem(id) {
  return PERFUME_CATALOG.find((item) => item.id === id) || PERFUME_CATALOG[0];
}
